### ISSUE TITLE
Oracle samples file not found

### ISSUE THREAD

**Issue by ishalyminov** [williamSYSU/TextGAN-PyTorch#1]
I get this at the very beginning, during the Oracle instance creation:

```
Traceback (most recent call last):
  File "main.py", line 93, in <module>
    inst = instruction_dict[cfg.run_model](opt)
  File "/scratch/ishalyminov/data/TextGAN-PyTorch/instructor/oracle_data/leakgan_instructor.py", line 25, in __init__
    super(LeakGANInstructor, self).__init__(opt)
  File "/scratch/ishalyminov/data/TextGAN-PyTorch/instructor/oracle_data/instructor.py", line 36, in __init__
    self.oracle_samples = torch.load(cfg.oracle_samples_path)
  File "/home/ishalyminov/miniconda3/envs/textgan_pytorch/lib/python3.6/site-packages/torch/serialization.py", line 382, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'pretrain/oracle_data/oracle_samples_NUM10000_lstm.pt'
```

**Comment by williamSYSU** [comment]
Thanks for your remind, I have fixed this bug (please refer to <code>instructor/instructor.py</code>)

**Comment by ishalyminov** [comment]
Thank you!
