### ISSUE TITLE
error about dataset

### ISSUE THREAD

**Issue by saharjandaghy** [williamSYSU/TextGAN-PyTorch#28]
When I use my dataset，it happens
could you help me?

training arguments:
>>> if_test: False
>>> run_model: seqgan
>>> k_label: 2
>>> dataset: obama
>>> model_type: vanilla
>>> loss_type: rsgan
>>> if_real_data: True
>>> cuda: True
>>> device: 0
>>> shuffle: False
>>> gen_init: truncated_normal
>>> dis_init: uniform
>>> samples_num: 10000
>>> vocab_size: 8077
>>> mle_epoch: 150
>>> clas_pre_epoch: 10
>>> adv_epoch: 2000
>>> inter_epoch: 15
>>> batch_size: 64
>>> max_seq_len: 148
>>> start_letter: 1
>>> padding_idx: 0
>>> gen_lr: 0.01
>>> gen_adv_lr: 0.0001
>>> dis_lr: 0.0001
>>> clip_norm: 5.0
>>> pre_log_step: 10
>>> adv_log_step: 20
>>> train_data: dataset/obama.txt
>>> test_data: dataset/testdata/obama_test.txt
>>> temp_adpt: exp
>>> temperature: 1
>>> ora_pretrain: True
>>> gen_pretrain: False
>>> dis_pretrain: False
>>> adv_g_step: 1
>>> rollout_num: 16
>>> gen_embed_dim: 32
>>> gen_hidden_dim: 32
>>> goal_size: 16
>>> step_size: 4
>>> mem_slots: 1
>>> num_heads: 2
>>> head_size: 256
>>> d_step: 5
>>> d_epoch: 3
>>> adv_d_step: 5
>>> adv_d_epoch: 3
>>> dis_embed_dim: 64
>>> dis_hidden_dim: 64
>>> num_rep: 64
>>> use_nll_oracle: True
>>> use_nll_gen: True
>>> use_nll_div: True
>>> use_bleu: True
>>> use_self_bleu: True
>>> use_clas_acc: True
>>> use_ppl: False
>>> log_file: log/log_0125_1829_54.txt
>>> save_root: save/20200125/obama/seqgan_vanilla_lt-rsgan_sl148_temp1_T0125_1829_54/
>>> signal_file: run_signal.txt
>>> tips: 
====================================================================================================
Traceback (most recent call last):
  File "main.py", line 134, in <module>
    inst = instruction_dict[cfg.run_model](opt)
  File "/home/drriyahi/Desktop/obama/instructor/real_data/seqgan_instructor.py", line 23, in __init__
    super(SeqGANInstructor, self).__init__(opt)
  File "/home/drriyahi/Desktop/obama/instructor/real_data/instructor.py", line 72, in __init__
    self.ppl = PPL(self.train_data, self.test_data, n_gram=5, if_use=cfg.use_ppl)
AttributeError: 'SeqGANInstructor' object has no attribute 'train_data'

**Comment by williamSYSU** [comment]
Have you put the `obama.txt` into `./dataset` directory?

**Comment by Monamour716** [comment]
> 当我使用我的数据集时，你能帮我吗？
> 
> 训练参数：
> 
> > > > if_test：假 run_model：seqgan k_label：2 数据集：奥巴马model_type：香草 loss_type：RSGAN if_real_data：真 cuda：真 设备：0 shuffle：假 gen_init：truncated_normal dis_init：均匀 samples_num：10000 vocab_size：8077 mle_epoch：150 clas_pre_epoch：10 adv_epoch：2000inter_epoch： 15 batch_size： 64 max_seq_len： 148 start_letter： 1 padding_idx： 0 gen_lr： 0.01 gen_adv_lr： 0.0001 dis_lr： 0.0001 clip_norm： 5.0 pre_log_step： 10 adv_log_step： 20 train_data： dataset/obama.txt test_data： dataset/testdata/obama_test.txt temp_adpt： exp 温度： 1 ora_预训练：对 gen_pretrain：错 dis_pretrain：错 adv_g_step：1 rollout_num：16 gen_embed_dim：32 gen_hidden_dim：32 goal_size：16 step_size：4 mem_slots：1 num_heads：2 head_size：256 d_step：5 d_epoch：3 adv_d_step：5 adv_d_epoch：3 dis_embed_dim：64 dis_hidden_dim：64 num_rep：64 use_nll_oracle：对 use_nll_gen：对 use_nll_div：对 use_bleu：对 use_self_bleu：对 use_clas_acc：对 use_ppl：错 log_file：日志/log_0125_1829_54.txt save_root：保存/20200125/奥巴马/seqgan_vanilla_lt-rsgan_sl148_temp1_T0125_1829_54/ signal_file：run_signal.txt提示： ==========seqgan_instructor.py  real_data[cfg.run_model](opt) instruction_dict main.py====================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================**init**（opt） 文件“/home/drriyahi/Desktop/obama/instructor/real_data/instructor.py”，第 72 行，**init** self.ppl = PPL（self.train_data， self.test_data， n_gram=5， if_use=cfg.use_ppl） AttributeError：“SeqGANInstructor”对象没有属性“train_data”

Did you succeed in debugging?

**Comment by Babasulaiman** [comment]
Yeah I put my data into a dataset folder and the model trained well. What I'm battling with now is plotting the graph and accessing the generated text file in return. Please it seems it's been encoded which I don't understand how to decode it and get the synthetic files in human readable format @williamSYSU @saharjandaghy
