### ISSUE TITLE
Training catGAN with a custom dataset: AttributeError: 'CatGANInstructor' object has no attribute 'train_samples_list'

### ISSUE THREAD

**Issue by julfr** [williamSYSU/TextGAN-PyTorch#66]
Hi,

Could you please advise what's the way to train catGAN on a custom, real dataset?
I modified `text_process.py` and `config.py` and now get an error:
```
Traceback (most recent call last):
  File "main.py", line 167, in <module>
    inst = instruction_dict[cfg.run_model](opt)
  File "/home/.../TextGAN-PyTorch/instructor/real_data/catgan_instructor.py", line 63, in __init__
    self.all_train_data = CatGenDataIter(self.train_samples_list)
AttributeError: 'CatGANInstructor' object has no attribute 'train_samples_list'
```

**Comment by julfr** [comment]
@williamSYSU 
@ishalyminov
